name: Compile Deno

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
      skip_compile:
        description: Skip Compilation
        default: "false"

jobs:
  release_metadata:
    name: Get Release Upload Metadata
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.get_upload_metadata.outputs.upload_url }}
      prerelease: ${{ steps.get_upload_metadata.outputs.prerelease }}
      version: ${{ steps.get_upload_metadata.outputs.version }}
    steps:
      - id: get_upload_metadata
        run: |
          export VERSION="${{ github.event.inputs.version || github.ref }}"
          VERSION="${VERSION#refs/tags/}"
          response=$(curl -L -s -H "Accept: application/json" https://api.github.com/repos/lukechannings/docker-deno/releases)
          release=$(echo $response | jq ".[]|select(.tag_name==\"${VERSION}\")")
          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=upload_url::$(echo $release | jq -r ".upload_url")"
          echo "::set-output name=prerelease::$(echo $release | jq -r ".prerelease")"
  compile:
    runs-on: macos-12
    needs: release_metadata
    name: "Compile ${{ matrix.target }}"
    if: ${{ github.event.inputs.skip_compile == 'false' }}
    strategy:
      matrix:
        target:
          - linux-arm64
          # 32-bit ARM isn't supported in QEMU because of this bug:
          # - https://bugs.launchpad.net/qemu/+bug/1805913
          # - https://github.com/rust-lang/cargo/issues/7451
          # - https://github.com/rust-lang/cargo/issues/8719
          # I've disabled it for the time being.

          # - linux-arm
    steps:
      - run: |
          brew install docker colima
          colima start --cpu 3 --memory 13 --disk 100
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile Deno
        run: |
          platform=$(node -p "'${{ matrix.target }}'.replace(/-/g, '/')")
          echo "Building for ${platform}"
          docker build -t deno-build --build-arg DENO_VERSION=${GITHUB_REF#refs/tags/} --platform=${platform} --file ./Dockerfile.compile .
          docker run --rm --platform=${platform} -v $(pwd):/pwd deno-build cp /deno/target/aarch64-unknown-linux-gnu/release/deno /pwd/
          zip deno-${{ matrix.target }}.zip ./deno
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release_metadata.outputs.upload_url }}
          asset_path: ./deno-${{ matrix.target }}.zip
          asset_name: deno-${{ matrix.target }}.zip
          asset_content_type: application/zip
  build-docker:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: [ release_metadata, compile ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        if: |
          !startsWith("canary-", "${{ needs.release_metadata.outputs.version }}")
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: VERSION=${{ needs.release_metadata.outputs.version }}
          tags: |
            lukechannings/deno:${{ needs.release_metadata.outputs.version }}
            lukechannings/deno:latest
      - name: Build and push (Canary)
        uses: docker/build-push-action@v2
        if: startsWith("canary-", "${{ needs.release_metadata.outputs.version }}")
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: VERSION=${{ needs.release_metadata.outputs.version }}
          tags: |
            lukechannings/deno:${{ needs.release_metadata.outputs.version }}

